### ISSUE TITLE
User can view a list of breweries in their city.

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/ajax-project#1]
## Plan
Create a responsive page where users can view a list of breweries near them.

## Wireframe
![Browse Breweries](https://user-images.githubusercontent.com/68713535/98613324-e95e7b00-22aa-11eb-9891-d2b1b5b990f9.png)

## Task List:

- [x] Pick a font.
- [x] Create app header w/ app name.
- [x] Create app footer with search icon and favorites icon.
- [x] Create location input field. 
- [x] Create temporary HTML with brewery options to simulate layout.  
- [x] Style to match wireframe
- [x] Listen for input events on the location input field.
- [x] Edit HTML and CSS to have image as the background for each brewery option
- [x] Clean up styling/bugs.
- [x] Declare a variable that holds XMLHTTP request data.
- [x] Create a 'welcome' data view that shows a welcome message and a form to enter their city
- [x] Create a 'brewery-options' data view that shows the list of brewery options in their city.
- [x] Create a view swapping function that shows the current view and hides all others.
- [x] Create a function that creates a dom tree modeling the HTML
- [x] Update formSubmitted function to assign api results to data model and loop through the results and use renderOptions function to populate HTML.
- [x] make footer/header fixed to bottom/top of page
- [x] delete temporary HTML data, clean code, adjust any styling, fix any bugs
