### ISSUE TITLE
User can view the details of a brewery.

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/ajax-project#2]
## Plan
User can click on a specific brewery and see more details.

## Wireframe
![Selected Brewery](https://user-images.githubusercontent.com/68713535/98614397-35122400-22ad-11eb-8a20-ff633ce88d6b.png)

## Task List
- [x] update HTML  to add a new data view for brewery details - populate with temporary data.
- [x] style to match figma
- [x]  Listen for click events on divs for any brewery option.
- [x] Create a function that handles this click event and switches to the 'brewery-details' data view if an option is selected.
- [x] update the viewSwapping function to show brewery details data-view and hide all others.
- [x] make sure brewery details match the brewery clicked.
- [x] add click event listener to search button on footer
- [x] create function on search button listener that swaps back to the 'welcome' data view
 - [x] clean code, fix any styling, delete any unnecessary styling, delete temp html, fix bugs
