### ISSUE TITLE
User can favorite a brewery.

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/ajax-project#3]
## 📐 Plan

User can add a brewery to a list of their favorites

## 🖼️ Wireframe

![Browse Breweries](https://user-images.githubusercontent.com/68713535/98614721-d8633900-22ad-11eb-8b7a-80e603b5a4f6.png)
![Selected Brewery](https://user-images.githubusercontent.com/68713535/98614725-da2cfc80-22ad-11eb-8576-8141362168dd.png)

## ✅ Task List
- [x] Listen for click events on the 'add to favorites' button
- [x] Add a favorites property to data model
- [x] Create a function that runs when the 'add to favorites' event fires.
- [x] Save brewery details to favorites array
- [x] Save favorites array to local storage using 'beforeunload' event listener on the window.
- [x] listen to the document for 'domContentLoaded' event and get the favorites data from local storage and assign to the favorites array.
- [x] add a back button to brewery details page.
- [x] add an event listener to back button to take the user back to options list
- [x] clean code, fix any bugs, test all functionality
