### ISSUE TITLE
User can view favorites list.

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/ajax-project#4]
## 📐 Plan

User can view their favorite breweries in a dedicated favorites page

## 🖼️ Wireframe

![Favorites page](https://user-images.githubusercontent.com/68713535/98614785-034d8d00-22ae-11eb-83c5-499e9421a424.png)

## ✅ Task List
- [x] create a new data view in the HTML for the favorites page.
- [x] update the viewSwapping function to show this page and hide all others when the view is on favorites.
- [x] change the header name from Brew Find to Favorites when the view is switched to favorites.
- [x] Listen for click events on the star at the footer  & switch the view to favorites.
- [x] Create a new function called renderFavorites that adds the favorites to the favorites page.  you cannot use render options as the data in brewArray is different than favorites array.
- [x] clean code, adjust any styling, fix any bugs, test all functionality
