### ISSUE TITLE
User can remove a brewery from favorites.

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/ajax-project#5]
## 📐 Plan

User can remove a brewery from their favorites

## 🖼️ Wireframe

![Favorites page](https://user-images.githubusercontent.com/68713535/98614833-1bbda780-22ae-11eb-9cca-54e08348a1bb.png)

## ✅ Task List
- [x] Update data model to include 'favorited' property with boolean value on selected property.
- [x]  Update the addToFavorites function to switch the favorited boolean when the user clicks add to favorites.
- [x] create a function that removes a selected item from the favorites array.
- [x] Update the favorites button event listener to include a conditional - if favorited is false run addToFavorites function, if favorited is true, run removeFromFavorites function.
- [x] ensure that the favorites page only shows current favorites
- [x] enable the user to click on a brewery in the favorites data-view and view brewery details.
- [x] clean code, fix bugs
