### ISSUE TITLE
User can rate & review a brewery.

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/ajax-project#6]
## 📐 Plan

User can rate and review a brewery

## 🖼️ Wireframe

![Selected Brewery](https://user-images.githubusercontent.com/68713535/98614893-40b21a80-22ae-11eb-9192-0b906f7b2b36.png)

## ✅ Task List
- [x] Create a new data view in the HTML for a review form.
- [x] Style review form
- [x] Update the view swapping function to show this data-view and hide all others.
- [x] Listen for click events on the write a review button.
- [x] Swap to review form when this event fires.
- [x] Update viewSwapping function to be more efficient/scaleable
- [x] Listen for submit events on the review form and create a new object with that review and add the review to the variable called reviews in data model
- [x] save the reviews array to local storage.
 - [x] get the reviews from local storage when the document is loaded.
- [x] create temporary html that shows a published review
- [x] style review box
- [x] create a function that renders reviews to the dom.
- [x] Update the optionSelected function to loop through the reviews array and add any matching reviews to the dom.
- [x] delete temporary HTML
- [x] add a click listener to the rating stars, depending on the star clicked color that red and all the stars below it red.  any stars above the selected should be gray.
- [x] save the new rating to only the selected brewery.
- [x] save ratings to local storage on beforeUnload and get ratings from local storage on DOMContent loaded
- [x] clean code, fix any bugs, test all functionality
